- **Nama:** Nabila Alawiyah
- **Email:** nabilaalawiyah.25@gmail.com
- **ID Dicoding:** nabila_alawiyah_B1OF

# A. Library

In [1]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 1.7 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [2]:
!pip install pipreq

Collecting pipreq
  Downloading pipreq-0.4.tar.gz (8.2 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pipreq
  Building wheel for pipreq (setup.py) ... done
  Created wheel for pipreq: filename=pipreq-0.4-py3-none-any.whl size=6368 sha256=e7c70a42cd7ba7fb617553cebe26942a11f4c8e9b2ad2b795ad8aa6ca6232675
  Stored in directory: /root/.cache/pip/wheels/e1/7d/81/849342a218540b2c6f7550c96a2f30415d08ae5b332727e282
Successfully built pipreq
Installing collected packages: pipreq
Successfully installed pipreq-0.4

In [3]:
# Import library google_play_scraper untuk mengakses ulasan dan informasi aplikasi dari Google Play Store.
from google_play_scraper import app, reviews, Sort

# Import csv
import csv

# Import pandas untuk manipulasi dan analisis data
import pandas as pd


# Import library untuk mendownload hasil ulasan dalam file csv
from google.colab import files

# B. Scrapping Data

In [6]:
# Mengambil hingga 20.000 ulasan paling relevan dari aplikasi dengan ID 'com.bcadigital.blu' di Google Play Store
scrapreview, continuation_token = reviews(
    'com.bcadigital.blu',            # ID aplikasi yang ingin diambil ulasannya
    lang='id',                   # Bahasa default ulasan yang diambil adalah Bahasa Indonesia
    country='id',                # Ulasan diambil dari pengguna yang berada di Indonesia
    sort=Sort.MOST_RELEVANT,     # Ulasan diurutkan berdasarkan relevansi tertinggi
    count=20000                  # Menentukan jumlah maksimal ulasan yang diambil yaitu 20.000
)

In [7]:
# Menyimpan ulasan yang telah diambil ke dalam file CSV bernama 'ulasan_tiket_dot_com.csv'
with open('ulasan_blu.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Review'])  # Judul kolom (header) di file CSV
    for review in scrapreview:
        writer.writerow([review['content']])  # Menuliskan isi ulasan ke dalam baris CSV satu per satu

In [8]:
pd.options.mode.chained_assignment = None  # Mematikan peringatan tentang modifikasi data yang dilakukan secara chaining

# Mengonversi data ulasan (scrapreview) menjadi DataFrame
review_app = pd.DataFrame(scrapreview)

# Melihat beberapa baris awal dari DataFrame
review_app.head()

# Menyimpan data ulasan ke dalam file CSV tanpa menyertakan indeks
review_app.to_csv('ulasan_blu.csv', index=False)

In [9]:
# Menampilkan lima baris pertama dari DataFrame app_reviews_df
review_app.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,e6135886-f9b9-426a-8cff-7afe90716f52,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Suka sih transaksi pakai aplikasi Blu by BCA, ...",3,2,1.63.10,2025-03-25 11:34:42,"Hai, Kak Muhammad Dava Wardhana. Terima kasih ...",2025-03-25 11:59:23,1.63.10
1,4c538f12-7d90-426f-a9ff-58fa48dfde9b,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"cukup baik, tolong perbaiki : 1. Tolong beri w...",4,5,1.63.10,2025-04-02 01:55:29,"Hai, Kak Sandi Wahyudi. Maaf atas ketidaknyama...",2025-04-02 02:40:05,1.63.10
2,1a4c92d3-85fb-427a-862a-c1d3a616210d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Baru aja Daftar kemarin, kayaknya sekarang sud...",4,2,1.63.10,2025-04-05 00:06:59,"Hai, Kak Rizky Padilah. Maaf atas ketidaknyama...",2025-04-05 00:57:09,1.63.10
3,07732b95-3c92-4c44-b644-d9474ed88e9e,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Sudah beberapa kali mau bayar atau mau transfe...,1,4,1.63.10,2025-04-07 07:31:59,"Hai, Kak Revina. Maaf atas ketidaknyamanannya....",2025-04-07 07:52:58,1.63.10
4,5db5e696-a2b5-4286-ab96-601349fd56f4,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,secara keseluruhan fitur mantap mudah digunaka...,3,6,1.63.10,2025-03-27 16:57:28,"Hai, Kak Deca. Maaf atas ketidaknyamanannya. K...",2025-03-27 17:15:04,1.63.10

In [10]:
# Mengetahui jumlah baris dan kolom review_app
review_app.shape

(20000, 11)

In [11]:
# Mengetahui info datatype tiap kolom
review_app.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              20000 non-null  object
 1   userName              20000 non-null  object
 2   userImage             20000 non-null  object
 3   content               20000 non-null  object
 4   score                 20000 non-null  int64
 5   thumbsUpCount         20000 non-null  int64
 6   reviewCreatedVersion  17533 non-null  object
 7   at                    20000 non-null  datetime64[ns]
 8   replyContent          20000 non-null  object
 9   repliedAt             20000 non-null  datetime64[ns]
 10  appVersion            17533 non-null  object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 1.7+ MB

In [12]:
# Menyimpan data frame baru dengan menghapus bari yang memiliki missing values
clean_df = review_app.dropna()

clean_df.shape

(17533, 11)

In [13]:
#menghapus kolom yang tidak dibutuhkan
clean_df =clean_df.drop(['reviewId', 'userName', 'userImage','thumbsUpCount', 'reviewCreatedVersion', 'replyContent',
       'repliedAt', 'appVersion','at'], axis=1)
clean_df

                                                 content  score
0      Suka sih transaksi pakai aplikasi Blu by BCA, ...      3
1      cukup baik, tolong perbaiki : 1. Tolong beri w...      4
2      Baru aja Daftar kemarin, kayaknya sekarang sud...      4
3      Sudah beberapa kali mau bayar atau mau transfe...      1
4      secara keseluruhan fitur mantap mudah digunaka...      3
...                                                  ...    ...
19995                                               nice      5
19996                                                Oke      5
19997                                                 Ok      5
19998                                               Good      5
19999                                               Okay      5

[17533 rows x 2 columns]

In [14]:
# Menghapus indeks
df_pemodelan = clean_df.reset_index(drop=True)

In [15]:
# Mendownload dataset hasil scraping
files.download('ulasan_blu.csv')

# Mendownload dataset hasil preprocessing data
df_pemodelan.to_csv('ulasan_pemodelan.csv',index=False)
files.download('ulasan_pemodelan.csv')

print("file berhasil didownload!")

file berhasil didownload!

# C. Requirement txt

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [28]:
!pipreq /content/drive/MyDrive/kuliah/Penulisan\ Ilmiah/Program/dataset --scan-notebooks --force

usage: pipreq [-h] [--version] [-g] [-c] [-U] [-x] [packages]
pipreq: error: argument packages: can't open '/content/drive/MyDrive/kuliah/Penulisan Ilmiah/Program/dataset': [Errno 21] Is a directory: '/content/drive/MyDrive/kuliah/Penulisan Ilmiah/Program/dataset'